sudo: required
services:
- docker
language: bash
script:
# build image
- docker build -t andrevs/debian-python3 .
# test image
# - docker run spanghf37/knxd uname -a
## push image
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker tag andrevs/debian-python3 andrevs/debian-python3:latest
- docker push andrevs/debian-python3:latest
